"""
Deterministic offline demo.

The demo runs the real pipeline, with every gate enforced, against a fixture
repository. Only the inputs are scripted: the reproduction test and the patch
are read from files next to the fixture instead of being generated by a model.
Nothing in the production pipeline knows this scenario exists.
"""
from __future__ import annotations

import json
import os
import shutil
import subprocess
from dataclasses import dataclass

EXAMPLES_DIR = os.path.dirname(os.path.abspath(__file__))
RATE_CALCULATOR_DIR = os.path.join(EXAMPLES_DIR, "rate_calculator")


@dataclass
class DemoScenario:
    repo_dir: str
    issue_number: int
    issue_title: str
    issue_body: str
    repro_test_code: str
    patch_diff: str


def _read(path: str) -> str:
    with open(path, "r", encoding="utf-8") as f:
        return f.read()


def _git(repo_dir: str, *args: str) -> None:
    subprocess.run(
        ["git", *args],
        cwd=repo_dir,
        check=True,
        capture_output=True,
        text=True,
    )


def prepare_rate_calculator_demo(dest_dir: str) -> DemoScenario:
    """Copy the fixture into dest_dir as a fresh one-commit git repository."""
    repo_dir = os.path.join(dest_dir, "rate_calculator")
    shutil.copytree(os.path.join(RATE_CALCULATOR_DIR, "repo"), repo_dir)
    _git(repo_dir, "init", "-q")
    _git(repo_dir, "config", "user.name", "Cerberus Demo")
    _git(repo_dir, "config", "user.email", "demo@cerberus.invalid")
    _git(repo_dir, "config", "core.autocrlf", "false")
    _git(repo_dir, "add", "-A")
    _git(repo_dir, "commit", "-q", "-m", "Fixture: rate calculator with a zero-division bug")

    issue = json.loads(_read(os.path.join(RATE_CALCULATOR_DIR, "issue.json")))
    return DemoScenario(
        repo_dir=repo_dir,
        issue_number=issue["number"],
        issue_title=issue["title"],
        issue_body=issue["body"],
        repro_test_code=_read(os.path.join(RATE_CALCULATOR_DIR, "test_reproduce.py")),
        patch_diff=_read(os.path.join(RATE_CALCULATOR_DIR, "fix.diff")),
    )
